# Spring properties
spring:
  application:
    name: accounts-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    instanceId: qwe

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port