version: '2'

services:
  mysql:
    image: mysql:5.7.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ppmtcourse
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
